services:
  apache:
    image: ubuntu/apache2
    container_name: apache2-http
    ports:
      - "80:80"
    volumes:
      - ./config:/etc/apache2/sites-enabled
    command: >
      bash -c "
               a2enmod http2 &&
               apache2ctl -D FOREGROUND"
    restart: unless-stopped
    networks:
      - webhosting_network

networks:
  webhosting_network:
    driver: bridge